### ISSUE TITLE
Store: storing files on google storage

### ISSUE THREAD

**Issue by yanivyehu** [deweb-io/premium#3]
The store and the premium server has access to the same google storage bucket. 
While check of product permission is being done with the store api, the link to the product is retrieved from the premium server.

Plugin:
https://wordpress.org/plugins/wp-stateless/#who%20maintains%20this%20plugin%3F

**Comment by yanivyehu** [comment]
delivery of digital goods from google storage (upload them private)

https://woocommerce.com/document/digital-downloadable-product-handling/

**Comment by yanivyehu** [comment]
use the private goods in premium service

**Comment by israeldeweb** [comment]
So, for now we are removing GCS entirely, trusting the digital goods to have a public URL.
