### ISSUE TITLE
Paypal 

### ISSUE THREAD

**Issue by yanivyehu** [deweb-io/premium#5]
use of Paypal when purchasing a subscription (money should be divided to the vendor and too us (comission) avoiding us from paying to the vendor.

**Comment by israeldeweb** [comment]
Can a subscription payment be a `parallel payment` (and not a `chained payment`).

**Comment by yanivyehu** [comment]
From this article i learned what is the difference between PayPal payouts and parallel payments:
https://www.angelleye.com/paypal-payouts-vs-parallel-payments-for-marketplaces/ 
and clearly parallel payment is the thing that we want.

So the the plugin that supports it with PayPal is:
https://woocommerce.com/document/paypal-adaptive-payments/#:~:text=Parallel%20payments,merchants%20that%20provided%20the%20items.

but it is **deprecated**. 

The following links also support that PayPal it is not an option for us:
https://developer.paypal.com/docs/archive/adaptive-payments/ht-ap-parallelPayment-curl-etc/ 
https://www.paypal-community.com/t5/REST-APIs/Merchant-payments-parallel-split/m-p/1730457#M2173

**Comment by israeldeweb** [comment]
It's probably not relevant right now, but if push comes to shove, we *can* write our own plugin. And, and this should be discussed with Eyal (so I'm reopening the issue), chained payments may work as well, if they are sent first to the *vendor*.

**Comment by israeldeweb** [comment]
For now we are waiting for stripe.
